# Introduccion

El avance exponencial que hemos experimentado como sociedad, tanto en el
desarrollo de nuevas tecnologías (reflejado en el incremento del número
de patentes concedidas año con año, 391 mil patentes concedidas en 2019
comparado con 49 mil en 1963) [@Marco2015], como en el aumento del
volumen de información generada [@Holst2021], así como en el incremento
en la rapidez con la que podemos analizarla y extraer significado de
ella [@Davenport2013] aunado a un ambiente de inversión de mayor
incentidumbre [@Ahir2020] hace más crítica la evaluación de proyectos
previo a su implementación, dada la correlación existente entre el
aumento de incertidumbre y la disminución en la inversión [@Leahy1996].

El uso de técnicas cuantitativas para la toma de decisiones en sin lugar
a duda una idea que ha sido estudidada por más de seis lustros. John
Bishop, Robert Schlaifer y Howard Raiffa revolucionaron el concepto de
Toma de Decisiones por medio de la integración de conceptos de una
escuela de pensamiento estadístico en los años 50. En específico,
Raiffer y Schlaifer desarrollaron un método para cuantificar el
conocimiento subjetivo utilizando **Probabilidad Bayesiana Subjetiva**
mientras trabajaban en **Harvard Business School**
[@Mcdonald2017Golden], influenciando de esta manera a generaciones de
administradores educados en HBS (a través del curso de **Managerial
Economics Reporting and Control** o MERC) y por lo mismo, su efecto
debería de sentirse a través de la comunidad de negocios hasta hoy en
día. Sin embargo, resultados de un análisis de una encuesta a ejecutivos
de compañías de **Fortune 500** indican que las mayores barreras de
adopción eran [@Green1976survey]:

1.  Los beneficios de usar las técnicas no son claramente entendibles
    por los administradores
2.  Los administradores no tienen el conocimiento necesario respecto a
    técnicas cuantitativas
3.  Los administradores no fueron expuestos a técnicas cuantitativas al
    inicio de su entrenamiento.

La lista continúa. Sin embargo, este top 3 nos ayuda a ver cierta parte
de la problemática que se relaciona al entendimiento de los métodos
cuantitativos por parte de la administración de las empresas. Esto es un
problema importante que puede ser minimizado (al menos en parte) por el
uso de tecnologías disponibles hoy en día.

Para este trabajo, se busca comparar los resultados de decisión de
inversión, para tres proyectos de implementación de nuevas tecnologías
en la industria química, con base en los métodos cuantitativos:
Simulación Monte Carlo, Análisis de Sensibilidad, Valor Monetario
Esperado (EMV por sus siglas en inglés) y Matriz de Toma de Decisiones
[@Stefanovic2005]. Esto con el fin de mostrar la diferencia entre las
decisiones que se tomarían con cada uno de los métodos por separado y
cómo se puede combinar el uso de estos métodos para mejorar la toma de
decisiones.

El utilizar R, en específico RMarkdown y paquetes del tidyverse, nos
permite crear un marco de análisis el cual es fácil de actualizar
conforme se obtenga mayor (o nueva) información de la(s) inversión(es)
que está(n) intentando analizarse. En mi experiencia en la industria,
toma mucho tiempo utilizar herramientas distintas para el análisis de la
información y para la presentación de la misma (ej. Excel y PowerPoint,
si se utilizan las herramientas de Microsoft). Incluso si se intenta
utilizar esfuerzos de automatización para esto, como macros o código en
VBA, se requiere de mayor esfuerzo y es más fácil hacer cambios sobre
los documentos que causen errores al correr el código de automatización.

Los tres proyectos de implementación a ser evaluados; "Digitalización de
la agricultura", "Biotecnología Industrial" y "Medicina Personalizada";
estos fueron escogidos con base en el impacto que pueden llegar a tener,
además de que forman parte del cuadrante de tendencias disruptivas y con
fines económicos de la industria química descritos en: [@Falter2017].

\newpage

## Medicina Personalizada

Dado que las enfermedades son más similares a una "red" de actividades
aberrantes (comunicación y comportamiento celular, proteínas
multifuncionales, genes modificadores, etc.), que a una progresión
lineal de síntomas [@Li2015], la medicina personalizada puede ayudar a
determinar el tratamiento apropiado para un individuo con base en
grandes cantidades de información a nivel de población [@Ho2020].

La medicina personalizada o de precisión cuenta con dos acercamientos,
el primero involucra el uso de tecnologías para adquirir y validar
información de poblaciones, tales como análisis ómico de células y
descubrimiento de biomarcadores para su subsecuente aplicación a nivel
de paciente. El segundo, involucra el uso de tecnologías para adquirir y
evaluar la información de un individuo para su propio tratamiento. El
uso de ambos acercamientos se podría realizar a través de su
integración, de manera que la información de población se utilice para
guiar qué compuesto utilizar con base en la información genética de la
persona, seguido de una dosificación dinámica guiada por información del
individuo [@Ho2020].

Para la tecnología específica a evaluar de Medicina Personalizada,
escogimos una que queda bajo el segundo acercamiento. En específico, en
una solución para dosificación dinámica, la cual se encuentra al cerca
del final de la cadena de valor, es decir, de un método de producción de
las tabletas para cada individuo.

### Tabletas Personalizables

La tecnología, de Medicina Personalizada evaluada en este trabajo, está
enfocada al paso siguiente de los acercamientos descritos en la sección
anterior, en especial al segundo acercamiento con fines de dosificación
dinámica y patrón de liberación del compuesto activo en tabletas
impresas utilizando tecnología de impresión 3D.

El método propuesto por Neriah para resolver el problema de proveer
medicina personalizada a la población en general para individuos
específicos efectiva y eficientemente, es a través de la fabricación
versátil de tabletas utilizando moldes específicamente diseñados de
diferentes formas y tamaños con el fin de permitir la personalización de
los siguientes aspectos de una tableta: dósis, duración, perfil de
liberación y combinación de diferentes compuestos [@Neriah2020].

Este acercamiento para proveer medicina personalizada a la población en
general cuenta con sus desafíos logísticos, y de producción, los cuales
se podrían ver reflejados en costos operativos elevados. Continuaremos
esta discusión en la sección de resultados específica a esta tecnología.

#### Modelos de negocio

La implementación de esta tecnología se presta a dos modelos de negocio
similares, pero que divergen en el punto de producción de las tabletas
personalizadas. En el primer modelo de negocio la producción de las
tabletas personalizadas se lleva a cabo en un centro operativo que
atiende a un número definido de farmacias y hospitales que se encuentren
en la cercanía. Mientras que en el segundo modelo de negocio se producen
las tabletas en las farmacias o en los hospitales mismos.

En ambos casos el cliente final haría un chequeo inicial en el hospital
o la farmacia en donde, con la ayuda de un doctor y análisis del caso
particular del paciente, se determina la dosis, así como el perfil y
tiempo de liberación de los componentes de la tableta personalizada.
Esta información se agregaría a un expediente compartido en donde cada
orden contendría la información necesaria para producir las tabletas
según las especificaciones necesarias.

A continuación se muestran los diagramas que muestran los dos modelos de
negocio.

![Diagrama de modelo de negocio con unidades operativas con producción
semi-centralizada](Diagramas/TP_Business_Model_1.png){width="90%"}

![Diagrama de modelo de negocio con producción en cada punto de venta
(Farmacias / Hospitales)](Diagramas/TP_Business_Model_2.png){width="90%"}

\newpage